language: python
python:
  - "3.8"
cache: pip

jobs:
    include:
      - stage: "Tests"                # naming the Tests stage
        name: "urbanroute"
        install:
            # Install requirements and modules
            - pip install "git+https://urbanrouting-ci:$CLEANAIRTOKEN@github.com/alan-turing-institute/clean-air-infrastructure.git/#egg=pkg&subdirectory=containers/cleanair"
            - pip install -r requirements.txt
            # - pip install -e urbanroute
            # - pip install -e routex
        script:
            # Run tests with pytest
            - python -m pytest tests/test_urbanroute
            # Check linting with pylint
            - pylint urbanroute/*
            # Check black formatting would not make any chages
            - black --check */
            # Flake8 performs pyflakes, pycodestyle and McCabe complexity checks
            - flake8 --ignore=E203, W503